minipock0/amcl:
  ros__parameters:
    use_sim_time: False
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.0
    base_frame_id: "minipock0/base_footprint"
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: true
    set_initial_pose: true
    global_frame_id: "map"
    lambda_short: 0.1
    laser_likelihood_max_dist: 2.0
    laser_max_range: 3.0
    laser_min_range: 0.2
    laser_model_type: "likelihood_field"
    max_beams: 60
    max_particles: 500
    min_particles: 100
    odom_frame_id: "minipock0/odom"
    pf_err: 0.05
    pf_z: 0.99
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0
    resample_interval: 1
    robot_model_type: "nav2_amcl::DifferentialMotionModel"
    save_pose_rate: 0.5
    sigma_hit: 0.2
    tf_broadcast: true
    transform_tolerance: 5.0
    update_min_a: 0.2
    update_min_d: 0.25
    z_hit: 0.5
    z_max: 0.05
    z_rand: 0.5
    z_short: 0.05
    scan_topic: /minipock0/scan
    map_topic: /map # map topic to subscribe to

# tb3_0/amcl_map_client:
#   ros__parameters:
#     use_sim_time: True

# tb3_0/amcl_rclcpp_node:
#   ros__parameters:
#     use_sim_time: True