name: "Docker Test"

on:
  pull_request:
    paths: .devcontainer/Dockerfile

jobs:
  docker-test:
    uses: catie-aq/generic_workflows/.github/workflows/docker-test.yaml@main
    with:
        dockerfile: .devcontainer/Dockerfile
        ignore: DL3008, DL3015, SC1091
