name: Sync Readme to Notion

on:
  workflow_dispatch: # Allow manual trigger
  push:

jobs:
  sync_readme_to_notion:
    uses: catie-aq/eagle_workflows/.github/workflows/notion.yml@main
    with:
      notion-page-id: "3d2ee4afcd3b4ad981c40a10133c90d1"
    secrets:
      notion-token: ${{ secrets.NOTION_TOKEN }}
