name: Publish tag when a new version pushed on main

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  poetry-test:
    uses: catie-aq/ros_workflows/.github/workflows/ros-tag.yml@main
