name: Build & Test ROS 2 Packages

on: [ push, pull_request ] # Trig on push and pull request

jobs:
  build_and_test_ros2_package:
    runs-on: self-hosted # Use self-hosted runner
    strategy: # Define a matrix of ROS distributions and Docker images
      matrix:
        ros_distribution:
          - humble
          - rolling
        include:
          - docker_image: ubuntu:jammy
            ros_distribution: humble
            ros_version: 2
          - docker_image: ubuntu:jammy
            ros_distribution: rolling
            ros_version: 2

    container: # Use the Docker image defined in the matrix
      image: ${{ matrix.docker_image }}
    steps:
      - name: setup ROS environment
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: ${{ matrix.ros_distribution }}
      - name: build and test ROS 2
        if: ${{ matrix.ros_version == 2 }}
        uses: ros-tooling/action-ros-ci@v0.2
        with:
          package-name: ${{ github.repository }}
          target-ros2-distro: ${{ matrix.ros_distribution }}
          import-token: ${{ secrets.GITHUB_TOKEN }}