name: "ROS2 CI/CD"

on:
  workflow_dispatch:
  pull_request:

jobs:
  pre-commit:
    uses: catie-aq/generic_workflows/.github/workflows/pre-commit.yaml@main
  ros2-build-test:
    uses: catie-aq/ros_workflows/.github/workflows/ros2.yml@main
